# Site settings
title: Travis Baugh
email: travis.baugh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal web development and technology blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tbaugh.github.io" # the base hostname & protocol for your site
twitter_username: travis_baugh
github_username:  tbaugh

# Build settings
markdown: kramdown
